### PR TITLE
feat: make max_rotations configurable

### LINKED ISSUE #78: Flag for setting max number of used rows
Max number of "used" rows is currently hardcoded to `512`. We should make this value settable using a cli flag /  config field (possibly as part of `.json` config file update).

### PR DESCRIPTION
**Pull request by Genysys**
This PR makes the tensor max value configurable via a CLI arg

closes #78

### CODE REVIEW

**Comment by alexander-camuto** [comment]
Hey @Genysys  and @samtvlabs this looks great ! Added a few nitpicky comments re-naming and comments, otherwise looks great. Once those changes are made will run integration tests ☺️

**Comment by jasonmorton** [comment]
This is great and happy to have your contributions.  I think Dante's comments are not visible.  The main thing is that we should change the naming of this feature perhaps to "max_rotations," as that is how it is currently used (it is not the max tensor value or the max rows, since there may be more than one block of this size stacked vertically).

**Review by alexander-camuto — CHANGES_REQUESTED** [review]
Hey @Genysys and @samtvlabs this looks great ! Added a few nitpicky comments re-naming and comments, otherwise looks great. Once those changes are made will run integration tests ☺️

**Review by alexander-camuto — APPROVED** [review]
LGTM !

**Pull request merged**
