### PR TITLE
docs: gcn example

### PR DESCRIPTION
**Pull request by saeyoon17**
(WIP)
- Try enabling the training process with downsampled graphs.

Adds a GCN example.

### CODE REVIEW

**Comment by alexander-camuto** [comment]
@saeyoon17 can you add this to the CI pipeline :) ? you need to modify `tests/py_integration_tests.py` and `.github/rust.yaml`

**Comment by saeyoon17** [comment]
@alexander-camuto Sure! I’ll do that.

**Comment by saeyoon17** [comment]
@alexander-camuto Hi dante, I have a question. 
I had some troubling running the tests on the local due to the dependency issues in pypi packages. 
It may be due to my mac local environment.

It does pass when I remove all specific versions but this is not desirable.. right?
Onto the original dependency, we need to add versions for torch-scatter, torch-sparse, and torch-geometric. 
For me, those were:
```
“torch-scatter==2.1.0”,
“torch-sparse==0.6.16",
“torch-geometric==2.2.0”,
```
But was not able to check the compatibility with other package versions :(.
If the versions need to be specified, would it be possible to run CI with the versions?
(If that's the case, I can revert last commit and fit in the versions.)

**Comment by alexander-camuto** [comment]
Hey @saeyoon17 thanks for the question ! We should definitely keep the versions in for the CI pipeline. We've been bitten by versionless python tests in the past and I want to avoid that aha

**Review by alexander-camuto — APPROVED** [review]
Looks good ! tests are passing. Thank you so much. Will merge in a bit

**Pull request merged**
